services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5

  bun:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:80'
    env_file:
      - .env
    depends_on:
      - mongo

